# Flower test case
initial_mesh_size: 0.8

# Uniform refinement
# iterations_number: 5
# refinement_method: "uniform"

# Adaptive refinement
iterations_number: 18
refinement_method: "H10"

bbox:
- [-4.5, 4.5]
- [-4.5, 4.5]
exact_error: false
ref_degree: 2
marking_parameter: 0.3
use_fine_space: false
box_mode: false
finite_element_degree: 1
levelset_degree: 1
boundary_detection_degree: 4
quadrature_degree: null
stabilization_parameter: 1.0
save_output: true