# Product of sines with pyramid levelset test case
initial_mesh_size: 0.15

# Uniform refinement
# iterations_number: 6
# refinement_method: "uniform"

# Adaptive refinement
iterations_number: 18
refinement_method: "H10"

bbox:
- [-0.75, 0.75]
- [-0.75, 0.75]
exact_error: true
marking_parameter: 0.3
use_fine_space: false
box_mode: false
finite_element_degree: 1
levelset_degree: 1
boundary_detection_degree: 1
quadrature_degree: null
stabilization_parameter: 1.0
save_output: true